name: personavey
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  rflutter_alert: ^2.0.4

  gap: ^2.0.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore:
  flutter_facebook_auth: ^4.4.0+1
  provider: ^6.0.3
  stacked: ^2.3.13
  stacked_services: ^0.9.2
  build_runner: ^2.1.11
  stacked_generator: ^0.5.6
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true
  assets:
    - images/
